feat: added analytics system (VF-1240)
voiceflow/google-runtime pull request #116
Opened 2021-07-05 21:24 UTC by xavidop

**Fixes or implements VF-1240 **

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ] title of PR reflects the branch name
- [ ] all commits adhere to conventional commits
- [ ] appropriate tests have been written
- [ ] all the dependencies are upgraded

2021-07-06 13:19 UTC, leartgjoni-voiceflow requested changes
looks good, but I think we should be adding this same logic to the `dialogflow` platform as well [here](https://github.com/voiceflow/google-client/blob/72fd8806b7ac69669111e0274c15a347f9c84e71/lib/services/dialogflow/index.ts#L24)

2021-07-06 13:19 UTC, leartgjoni-voiceflow commented on lib/services/googleV2/request/index.ts
> +      };
the `request` var is being declared twice, we could move this up and init it once, and only change the type to `RequestType.MEDIA_STATUS` later if needed

2021-07-06 22:01 UTC, jonahsnider requested changes

2021-07-06 22:40 UTC, jonahsnider approved these changes

2021-07-07 09:41 UTC, merged

2021-07-07 09:45 UTC, vf-service-account commented
:tada: This PR is included in version 1.29.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/google-runtime/releases/tag/v1.29.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: