feat: no-match/no-reply improvements (VF-2136)
voiceflow/google-runtime pull request #173
Opened 2021-11-30 17:57 UTC by z4o4z

**Fixes or implements VF-2136**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2021-12-01 04:03 UTC, DecathectZero requested changes

2021-12-01 04:03 UTC, DecathectZero commented on lib/services/runtime/handlers/interaction.ts
> +    if (nextId !== undefined) return nextId;
very important that you do this:
```suggestion
    if (nextId !== undefined) {
      runtime.turn.delete(T.REQUEST);
      return nextId;
    }
```
if you don't delete the request, the next interaction block will still try to handle it.

2021-12-01 04:05 UTC, DecathectZero commented on lib/services/runtime/handlers/capture.ts
> +    }
need to do this in the interaction block too?

2021-12-01 15:28 UTC, DecathectZero approved these changes

2021-12-02 09:28 UTC, z4o4z commented on lib/constants/flags.ts
> +  NO_REPLIES_COUNTER = 'noRepliesCounter',
yeah, will rename it

2021-12-02 14:13 UTC, merged

2021-12-02 14:19 UTC, vf-service-account commented
:tada: This PR is included in version 1.44.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/google-runtime/releases/tag/v1.44.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: