feat: check action in no input handler (VF-3040)
voiceflow/google-runtime pull request #203
Opened 2022-04-22 22:29 UTC by trs

**Fixes or implements VF-3040**

### Brief description. What is this change?

Check the request `action` for a no input action and handle that accordingly.

2022-04-22 23:25 UTC, jonahsnider commented on lib/services/runtime/handlers/noInput.ts
> +    return runtime.turn.get<IntentRequest>(T.REQUEST)?.payload?.action === NO_INPUT_PREFIX;
could you please explain this change? i'm a bit confused since the variable `NO_INPUT_PREFIX` seems like you'd want to do a `startsWith` check rather than `===`

2022-04-22 23:58 UTC, DecathectZero commented on lib/services/runtime/handlers/noInput.ts
> +    return runtime.turn.get<IntentRequest>(T.REQUEST)?.payload?.action === NO_INPUT_PREFIX;
so what is awkward about this handler and the structure of this google runtime, is that it handles for both google actions (google assistant) and for dialogflow ES. Let's check that this doesn't break it for google actions no input.
https://developers.google.com/assistant/conversational/intents#list_of_intents

2022-04-23 00:05 UTC, DecathectZero requested changes

2022-04-23 00:05 UTC, DecathectZero commented on lib/services/runtime/handlers/noInput.ts
> +    return runtime.turn.get<IntentRequest>(T.REQUEST)?.payload?.action === NO_INPUT_PREFIX;
You might want to do a `||` with the prior statement. 
Google Actions does this: 
```
actions.intent.NO_INPUT_1

actions.intent.NO_INPUT_2

actions.intent.NO_INPUT_FINAL
```
thing which is why we had the `startsWith`

2022-04-23 02:20 UTC, trs commented on lib/services/runtime/handlers/noInput.ts
> +    return runtime.turn.get<IntentRequest>(T.REQUEST)?.payload?.action === NO_INPUT_PREFIX;
With DF ES, we create a no input event that explicitly sends the action `actions.intent.NO_INPUT`, that's why I changed it to equality. For that case, I should have changed the name for sure.
Can see: https://developers.google.com/assistant/df-asdk/reprompts and https://developers.google.com/assistant/df-asdk/reference/intents
But given that this also handles Google Actions, Ty has the right idea with checking both.

2022-04-23 02:20 UTC, trs commented on lib/services/runtime/handlers/noInput.ts
> +    return runtime.turn.get<IntentRequest>(T.REQUEST)?.payload?.action === NO_INPUT_PREFIX;
Thanks for clarifying that! I will make the change.

2022-04-23 03:08 UTC, DecathectZero commented on lib/services/runtime/handlers/noInput.ts
> +    return !!payload?.action?.startsWith(NO_INPUT_PREFIX) || !!payload?.intent?.startsWith(NO_INPUT_PREFIX) || false;
isn't some of the this logic superfluous? 
```suggestion
    return !!(payload?.action?.startsWith(NO_INPUT_PREFIX) || payload?.intent?.startsWith(NO_INPUT_PREFIX))
```

2022-04-23 03:21 UTC, DecathectZero approved these changes

2022-04-23 05:30 UTC, DecathectZero commented
bors r+

2022-04-23 05:38 UTC, closed without merging