ci(circleci): added sonar and git hooks (CORE-4768)
voiceflow/google-runtime pull request #70
Opened 2021-01-22 19:55 UTC by xavidop

**Fixes or implements CORE-4768**

### Brief description. What is this change?

Added sonarcloud and git branch hooks

### Checklist

- [x] title of PR reflects the branch name
- [x] all commits adhere to conventional commits
- [ ] appropriate tests have been written
- [ ] all the dependendencies are upgraded

2021-01-26 17:32 UTC, frankgu968 commented
Can we disable the PR-label -> preview dev env as a check? We should still let it run, but can we not show it as a check? This wasn't possible about 6 months ago when I was working on this, but Github may have enabled that feature now...

2021-01-26 17:33 UTC, frankgu968 requested changes

2021-01-26 17:33 UTC, frankgu968 commented on tests/smoke/smokeTestRunner.ts
> +import '../../envSetup';
Can we standardize this to `@/envSetup`? same thing for the others above

2021-01-26 17:33 UTC, frankgu968 commented on config.ts
> +import './envSetup';
Can we use `@/envSetup`?

2021-01-26 19:05 UTC, xavidop commented on tests/smoke/smokeTestRunner.ts
> +import '../../envSetup';
done!

2021-01-26 19:05 UTC, xavidop commented on config.ts
> +import './envSetup';
done!

2021-01-26 19:07 UTC, frankgu968 approved these changes

2021-01-26 19:11 UTC, merged

2021-01-27 11:01 UTC, vf-service-account commented
:tada: This PR is included in version 1.15.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/google-runtime/releases/tag/v1.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: